In [115]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [117]:
df = pd.read_csv("loan_approval_dataset_200_rows.csv")
df.head(2)

,applicant_id,age,cibil_score,annual_income_inr,employment_type,years_employed,existing_loans,loan_amount_inr,loan_term_months,debt_to_income_ratio,loan_approved
0,APP0001,24,720,323448,Self-employed,4,2,350093,48,1.137,0
1,APP0002,51,622,1018039,Business,5,2,606816,24,0.403,1

In [119]:
df[df['loan_approved'] == 1]["loan_amount_inr"].sum()

np.int64(79812615)

In [121]:
kpi = {
    "total_applicants" : df['applicant_id'].count(),
    "total loan_distributed" : df[df['loan_approved'] == 1]["loan_amount_inr"].sum(),
    "total_loan_pass" : df[df['loan_approved'] == 1]["applicant_id"].count(),
    "avg cibil score" : df["cibil_score"].mean()

}
kpi

{'total_applicants': np.int64(200),
 'total loan_distributed': np.int64(79812615),
 'total_loan_pass': np.int64(84),
 'avg cibil score': np.float64(687.53)}

In [127]:
people_count = df.groupby(by = 'employment_type').agg(
    total_applicant = ("applicant_id", "count")
).reset_index()
people_count

  employment_type  total_applicant
0        Business               35
1        Salaried              107
2   Self-employed               58