In [31]:
import pandas as pd

df = pd.DataFrame({
    "Name": [
        "Rahul Sharma",
        " PRIYA SINGH ",
        "amit kumar",
        "Neha Gupta",
        "ROHIT VERMA"
    ],
    "Email": [
        "rahul@gmail.com",
        "priya@yahoo.com",
        "amit@gmail.com",
        "neha@company.com",
        "rohit@gmail.com"
    ],
    "City": [
        "jodhpur",
        "Jaipur",
        "Jodhpur",
        "Delhi",
        "Jaipur"
    ]
})

df

            Name             Email     City
0   Rahul Sharma   rahul@gmail.com  jodhpur
1   PRIYA SINGH    priya@yahoo.com   Jaipur
2     amit kumar    amit@gmail.com  Jodhpur
3     Neha Gupta  neha@company.com    Delhi
4    ROHIT VERMA   rohit@gmail.com   Jaipur

In [18]:
"rahul@gmail.com".split("@")[1]

'gmail.com'

In [27]:
df['user_name'] = df['Email'].str.split("@", expand= True)[0]
df['domain_name'] = df['Email'].str.split("@", expand= True)[1]

In [32]:
df

            Name             Email     City
0   Rahul Sharma   rahul@gmail.com  jodhpur
1   PRIYA SINGH    priya@yahoo.com   Jaipur
2     amit kumar    amit@gmail.com  Jodhpur
3     Neha Gupta  neha@company.com    Delhi
4    ROHIT VERMA   rohit@gmail.com   Jaipur

In [36]:
df[df["City"].str.contains("jodhpur", case = False, na= True)]

           Name            Email     City
0  Rahul Sharma  rahul@gmail.com  jodhpur
2    amit kumar   amit@gmail.com  Jodhpur

In [38]:
result = df[
    df["Email"].str.endswith(
        "@gmail.com",
        na=False
    )
]
result

           Name            Email     City
0  Rahul Sharma  rahul@gmail.com  jodhpur
2    amit kumar   amit@gmail.com  Jodhpur
4   ROHIT VERMA  rohit@gmail.com   Jaipur

In [39]:
df = pd.DataFrame({
    "Order": [
        "ORD-1025",
        "ORD-2048",
        "ORD-3099"
    ]
})
df

      Order
0  ORD-1025
1  ORD-2048
2  ORD-3099

In [41]:
df["Order_Number"] = df["Order"].str.extract(
    r"(\d+)"
)
df

      Order Order_Number
0  ORD-1025         1025
1  ORD-2048         2048
2  ORD-3099         3099

In [58]:
df = pd.DataFrame({
    "Study_Hours": [2, 3, 4, 5, 6, 7, 8, 9],
    "Marks": [45, 50, 55, 62, 68, 74, 81, 88],
    "Attendance": [65, 70, 72, 78, 80, 85, 90, 94]
})

df

   Study_Hours  Marks  Attendance
0            2     45          65
1            3     50          70
2            4     55          72
3            5     62          78
4            6     68          80
5            7     74          85
6            8     81          90
7            9     88          94

In [43]:
df["Marks"].agg(["count", "mean", "median", "std", "var", "min", "max"])

count       8.000000
mean       65.375000
median     65.000000
std        15.155739
var       229.696429
min        45.000000
max        88.000000
Name: Marks, dtype: float64

In [46]:
df["Marks"].quantile([0.3, 0.4])

0.3    55.7
0.4    60.6
Name: Marks, dtype: float64

In [56]:
df["Study_Hours"].corr(df["Marks"])
# [-1 , 1]

np.float64(-0.9985885353194072)

In [59]:
df.corr()  # correlation matrix

             Study_Hours     Marks  Attendance
Study_Hours     1.000000  0.998589    0.996386
Marks           0.998589  1.000000    0.997354
Attendance      0.996386  0.997354    1.000000

In [61]:

df["Study_Hours"].cov(df["Marks"])

np.float64(37.07142857142857)

In [62]:
df.cov()   # covariance matrix

             Study_Hours       Marks  Attendance
Study_Hours     6.000000   37.071429   24.571429
Marks          37.071429  229.696429  152.178571
Attendance     24.571429  152.178571  101.357143

In [63]:
departments = pd.Series(["IT", "HR", "IT", "Sales", "IT", "HR"])
departments

0       IT
1       HR
2       IT
3    Sales
4       IT
5       HR
dtype: str

In [64]:
departments.value_counts()

IT       3
HR       2
Sales    1
Name: count, dtype: int64

In [66]:
departments.value_counts(normalize=True).mul(100)  # percentage

IT       50.000000
HR       33.333333
Sales    16.666667
Name: proportion, dtype: float64

In [67]:
df = pd.DataFrame({
    "Date": [
        "2026-01-05", "2026-01-10", "2026-01-15",
        "2026-02-05", "2026-02-12", "2026-02-20",
        "2026-03-05", "2026-03-15", "2026-03-25"
    ],
    "Region": ["North", "South", "North", "South", "East", "North", "East", "South", "North"],
    "Product": ["Laptop", "Mobile", "Mobile", "Laptop", "Tablet", "Laptop", "Mobile", "Tablet", "Mobile"],
    "Sales": [85000, 45000, 50000, 90000, 35000, 95000, 55000, 40000, 60000],
    "Quantity": [5, 10, 8, 6, 7, 5, 11, 8, 12]
})
df["Date"] = pd.to_datetime(df["Date"])
df

        Date Region Product  Sales  Quantity
0 2026-01-05  North  Laptop  85000         5
1 2026-01-10  South  Mobile  45000        10
2 2026-01-15  North  Mobile  50000         8
3 2026-02-05  South  Laptop  90000         6
4 2026-02-12   East  Tablet  35000         7
5 2026-02-20  North  Laptop  95000         5
6 2026-03-05   East  Mobile  55000        11
7 2026-03-15  South  Tablet  40000         8
8 2026-03-25  North  Mobile  60000        12

In [68]:
kpis = {
    "total_sales": df["Sales"].sum(),
    "average_sale": df["Sales"].mean(),
    "total_quantity": df["Quantity"].sum(),
    "orders": len(df),
    "maximum_sale": df["Sales"].max()
}
kpis

{'total_sales': np.int64(555000),
 'average_sale': np.float64(61666.666666666664),
 'total_quantity': np.int64(72),
 'orders': 9,
 'maximum_sale': np.int64(95000)}

In [75]:
df = pd.DataFrame({
    "Region": ["North", "North", "South", "South"],
    "Product": ["Laptop", "Mobile", "Laptop", "Mobile"],
    "Sales": [100000, 60000, 80000, 50000]
},
)
df = df.set_index(["Region", "Product"])
df

                 Sales
Region Product
North  Laptop   100000
       Mobile    60000
South  Laptop    80000
       Mobile    50000

In [79]:
df.loc["North", "Laptop"]

Sales    100000
Name: (North, Laptop), dtype: int64

In [ ]:
index = pd.MultiIndex.from_tuples([
    ("North", "Laptop"),
    ("North", "Mobile"),
    ("South", "Laptop"),
    ("South", "Mobile")
], names=["Region", "Product"])

df = pd.DataFrame(
    {"Sales": [100000, 60000, 80000, 50000]},
    index=index
)

print(df)